export const ARR_DRAW_OPERATION = [
	"DRAW_PEN",
	"DRAW_ERASER",
	"DRAW_MIRROR",
	"DRAW_BACKET",
	"DRAW_RECTANGLE",
	"DRAW_LINE",
	"DRAW_REPLACE_RGB",
	"DRAW_CIRCLE",
	"SELECT_RECTANGLE",
	"SELECT_CROP",
	"UTILS_PICK_RGB",
]
